local rolelist = {
	['Gender Identity'] = {
		["Non-Binary"] = {"nb", "non binary"},
		["MtF"] = {"transwoman", "trans woman"},
		["FtM"] = {"transman", "trans man"},
		["Demigirl"] = {},
		["Demiboy"] = {},
		["Demifluid"] = {},
		["Bigender"] = {},
		["Genderfluid"] = {},
		["Genderflux"] = {},
		["Agenderflux"] = {},
		["Neutrois"] = {},
		["Agender"] = {},
		["Solarian"] = {},
		["Lunarian"] = {},
		["Stellarian"] = {},
		["Genderqueer"] = {},
		["Androgyne"] = {},
		["Male"] = {},
		["Female"] = {},
		["Intergender"] = {},
		["Trans Femme"] = {"transfemme", "trans fem", "transfem"},
		["Trans Masc"] = {"transmasc"},
		["Questioning Gender"] = {"questioning"},
		["Cis Male"] = {},
		["Cis Female"] = {},
	},
	['Presentation'] = {
		["Masc"] = {},
		["Femme"] = {},
		["Androgynous"] = {},
	},
	['Assigned Sex'] = {
		["Intersex"] = {},
		["AFAB"] = {"faab", "dfab"},
		["AMAB"] = {"maab", "dmab"},
	},
	['Pronouns'] = {
		["He/Him/His"] = {"he", "he/him"},
		["She/Her"] = {"she"},
		["They/Them/Their"] = {"they", "they/them"},
		["Fae/Faer/Faers"] = {"fae"},
		["Ey/Em/Eir"] = {"ey"},
		["Ce/Cir/Cirs"] = {"ce"},
		["Ne/Nem/Nir"] = {"ne"},
		["Zie/Hir/Hirs"] = {"zie"},
		["Xe/Xem/Xyrs"] = {"xe"},
		["Ve/Vir/Vis"] = {"ve"},
	},
	['Sexuality'] = {
		["Straight"] = {},
		["Heterosexual"] = {},
		["Gay"] = {},
		["Lesbian"] = {},
		["Bisexual"] = {"bi"},
		["Queer"] = {},
		["Pansexual"] = {"pan"},
		["Enbian"] = {},
		["Diamoric"] = {},
		["Aromantic"] = {"aro"},
		["Demiromantic"] = {},
		["Greyromantic"] = {},
		["Androromantic"] = {},
		["Homoromantic"] = {},
		["Heteroromantic"] = {},
		["Biromantic"] = {},
		["Panromantic"] = {},
		["Achillean"] = {},
		["Asexual"] = {"ace"},
		["Demisexual"] = {},
		["Greysexual"] = {"graysexual", "grey", "gray"},
		["Polysexual"] = {},
		["Quoisexual"] = {},
		["Quoiromantic"] = {},
		["Heteroflexible"] = {},
		["Homoflexible"] = {},
		["Polyamorous"] = {"poly"},
		["Monogamous"] = {"mono"},
		["Questioning Sexuality"] = {},
	},
	['Opt-In Roles'] = {
		["Gamer"] = {},
		["D&D - Isabelle"] = {"d&d isabelle", "dnd isabelle", "campaign isabelle"}
		["Hot Topic"] = {"hot-topic", "hottopic"},
		["Momiji Dev"] = {"momiji", "dev", "momijidev"},
		["18+"] = {"18"},
		["NSFW-Extras"] = {"nsfw extras"},
		["NSFW-Nb"] = {"nsfw nb"},
		["NSFW-Fem"] = {"nsfw fem"},
		["NSFW-Masc"] = {"nsfc masc"},
		["NSFW-Gen"] = {"nsfw gen"},
		["NSFW-Selfies"] = {"nsfw selfies"},
	},
}

return rolelist
